name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: visy-ani
          svg_out_path: github-contribution-grid-snake.svg

      # DEBUG STEP: This will show us all files that exist before the commit step
      - name: List files in the directory
        run: ls -R

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add github-contribution-grid-snake.svg
          if ! git diff --staged --quiet; then
            git commit -m "docs: generate contribution snake animation"
            git push
          else
            echo "No changes to commit."
          fi